### ISSUE TITLE
Version 1.0.4 does not have `Active environment` when right-clicking on `vcpkg-configuration.json`

### ISSUE THREAD

**Issue by mikisama** [ARM-software/vscode-environment-manager#1]
Type: Bug Report

**Describe the bug**
- OS and Version: WIN11 22h2
- VS Code Version: 1.81.1
- Extension Version: v1.0.4
- Target Device:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**Expected behavior**

The `vcpkg-configuration.json` is not in the root directory of the project. When I use version 1.0.4 of this extension, there is no `Active environment` when I right-click on `vcpkg-configuration.json`. But when I downgraded to v1.0.3, there was no such issue.

```tree
├─.vscode
├─mdk
│  │  vcpkg-configuration.json
└─source
```

**Screenshots**
- v1.0.4
![image](https://github.com/ARM-software/vscode-environment-manager/assets/41532794/3e626bfb-8f8f-4e1e-b7a4-b811abe589af)

- v1.0.3
![image](https://github.com/ARM-software/vscode-environment-manager/assets/41532794/3b813fe1-b457-43ba-8e98-90b4f3507b65)

**Comment by mcgordonite** [comment]
Hi @mikisama, thanks for the bug report. It looks like there is a bug in 1.0.4 when the vcpkg-configuration.json file is not at the root of the workspace. We'll get a fix out to you as soon as possible, but in the meantime you could copy the vcpkg-configuration.json to the root of the workspace to activate your environment.

**Comment by mikisama** [comment]
> Hi @mikisama, thanks for the bug report. It looks like there is a bug in 1.0.4 when the vcpkg-configuration.json file is not at the root of the workspace. We'll get a fix out to you as soon as possible, but in the meantime you could copy the vcpkg-configuration.json to the root of the workspace to activate your environment.

Thanks for your information.  Copying the vcpkg-configuration.json to the root of the workspace works for me.

**Comment by mcgordonite** [comment]
Version 1.0.5 released today should have a fix for this issue.
