### ISSUE TITLE
how to change default vcpkg folder

### ISSUE THREAD

**Issue by bricle** [ARM-software/vscode-environment-manager#11]
> vcpkg folder
> 
> The base ~/.vcpkg directory (%USERPROFILE%\.vcpkg on Windows) contains the following sub-folders:
> 
> artifacts: Installation folders of the tools.
> 
> downloads: Download images of the tools.
> 
> registries: A catalog of the tools available. The Update Tool Registry command retrieves the latest catalog.

That is the default vcpkg folder, but is there any way to change that to anathor path, very appreciate if anybody could give me some hint.

**Comment by thegecko** [comment]
There's a vcpkg root folder setting

**Comment by bricle** [comment]
> There's a vcpkg root folder setting

wors fine for me, thanks a lot.
