### ISSUE TITLE
Fail to activate arm tools community license 

### ISSUE THREAD

**Issue by LJ-Conqueror** [ARM-software/vscode-environment-manager#7]
When I need Armclang to build my Csolution, Keil Studio pack reminds me to activate Arm tools license, and I click **Activate Arm Keil MDK Community Edition**, but it always fails to do that, the tips and failure log like below:

![image](https://github.com/user-attachments/assets/c9e90bbb-0935-4b88-b92e-827a3ad08bda)

> Command-line: c:\Users\Vigor Wave\.vscode\extensions\arm.environment-manager-1.4.0-win32-x64\tools\armlm\bin\armlm.exe activate --server https://mdk-preview.keil.arm.com --product KEMDK-COM0
Version: 1.3.1+793d4108664647149047db9e9ace8d41085dca7d
Environment: 

> ERRO error creating capability response: Server was not able to process request correctly (FLXERR_RESPONSE_SERVER_ERROR)
I found I can't visit [https://mdk-preview.keil.arm.com](url), I have tried closing Windows Firewall, updating my Internet connection, and switching Chrome DNS, but All didn't work. 

Can anyone help me? Thanks.

**Comment by localbuilder** [comment]
Hi @LJ-Conqueror, 

I couldn't reproduce exactly the error you reported, but I do see problems with usernames containing white spaces, as in yours "Vigor Wave". I believe this should be supported and will raise a bug internally. Until this is fixed, I haven't got another workaround to offer than changing your username to not have white spaces. Doing a little bit of research on how to change the username on Windows (disclaimer: I'm not on Windows), it looks possible but is done differently depending on the exact version of Windows and account type. Hope this helps.

**Comment by LJ-Conqueror** [comment]
Hi @localbuilder I finally solved my  problem by changing my account username, and I do hope this bug will be fixed in the future.
Finally, I am very grateful for your help

**Comment by thegecko** [comment]
Glad you were able to fix your issue.
